<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Services\PhotoService;
use Symfony\Component\HttpFoundation\Response;

/**
 * Serves stored photographs.
 *
 * Public route, authorised by the URL signature alone — see PhotoService for why.
 * The `signed` middleware guarantees the URL was generated by this application and
 * has not expired; nothing else is required, and requiring a token here would break
 * `<img>` tags.
 *
 * No authorisation is done against the photo's owner because a signed URL is only
 * ever handed to a user who already passed the applicable policy. The expiry is
 * what limits how long a leaked URL stays useful.
 */
class PhotoController extends Controller
{
    public function __construct(private readonly PhotoService $photos) {}

    public function show(string $path): Response
    {
        $bytes = $this->photos->read($path);

        if ($bytes === null) {
            abort(404);
        }

        /*
         * No sniffing, and a private cache directive: the response is personal data
         * and must not be cached by a shared proxy.
         */
        return response($bytes, 200, [
            'Content-Type' => $this->mimeFor($path),
            'X-Content-Type-Options' => 'nosniff',
            'Cache-Control' => 'private, max-age=300',
        ]);
    }

    /** Derived from the extension we control when storing, not from user input. */
    private function mimeFor(string $path): string
    {
        return match (strtolower(pathinfo($path, PATHINFO_EXTENSION))) {
            'png' => 'image/png',
            'webp' => 'image/webp',
            'gif' => 'image/gif',
            default => 'image/jpeg',
        };
    }
}
