<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Give the punch trail a client id, making it the ledger for offline retries.
 *
 * THE BUG THIS FIXES
 *
 * Idempotency was keyed on `time_entries.client_uuid` alone, which works for a clock-in and
 * fails for a clock-out. `clockOut()` creates no new segment — it CLOSES the open one — so the
 * id the client sent for that clock-out was stored nowhere at all. A retry therefore found
 * nothing to match, closed the segment again, and the "nothing open" case then reported the
 * employee's own clock-out as out-of-order. A lost reply on a clock-out meant the punch was
 * refused, and the employee was left on the clock with no way to fix it at the screen.
 *
 * The trail is the right place for this, because it is the one table that records EVERY action:
 * the ones that open a segment, the ones that close one, and the ones that do neither. A ledger
 * that only covers creations cannot deduplicate closures.
 *
 * UNIQUE PER EMPLOYEE, not globally — and the distinction is a bug found while testing this.
 *
 * A client id is generated by one phone, so it is globally unique in practice. But the lookup
 * that uses this column is scoped to the employee, so a global index would mean two employees
 * who happened to reuse an id collided on INSERT and got a 500 — a punch refused for a reason
 * that has nothing to do with either of them, and one trivially caused on purpose.
 *
 * Keying the index on the employee as well matches exactly what the lookup asks ("has THIS
 * employee already applied THIS id?") and makes the constraint answer the same question the code
 * does. A client id is meaningless outside the employee it belongs to.
 *
 * MySQL and SQLite both allow repeated NULLs in a unique index, which matters: an ordinary online
 * punch has no client id and must not collide with every other one.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('punch_events', function (Blueprint $table) {
            /*
             * Nullable, because most punches arrive online with no id at all. Nullable is also
             * what keeps this additive: every existing row stays valid.
             */
            $table->char('client_uuid', 36)->nullable()->after('event');

            $table->unique(['employee_id', 'client_uuid']);
        });
    }

    public function down(): void
    {
        Schema::table('punch_events', function (Blueprint $table) {
            $table->dropUnique(['employee_id', 'client_uuid']);
            $table->dropColumn('client_uuid');
        });
    }
};
