<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Punch codes for each outlet.
 *
 * Two modes share one table because they are the same concept — a code that
 * proves someone was at an outlet — differing only in lifetime:
 *
 *   printed   expires_at NULL  — valid until explicitly revoked
 *   rotating  expires_at set   — short window, shown on a device
 *
 * "Latest applicable" is implemented by revoking: generating a new code for an
 * outlet kills the previous live one in the same transaction.
 *
 * PRINTED CODES DO NOT EXPIRE (decided 2026-09-16). A printed sheet stays valid
 * until a manager or the owner reprints it, on whatever ad hoc basis they choose —
 * not on a daily or weekly schedule. That is a deliberate trade-off: a printed
 * code identifies the OUTLET, not the person's presence, so anyone who photographs
 * it can punch from home and nothing here can tell. The compensating controls are
 * the punch photo, the shift window, the anomaly queue, and reprinting.
 *
 * The practical consequence for the build: REPRINTING IS THE REVOKE MECHANISM and
 * must be one obvious action on the Codes screen. If reprinting is awkward, a
 * leaked code stays live, so this is a usability requirement rather than a nicety.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('outlet_tokens', function (Blueprint $table) {
            $table->id();
            $table->foreignId('outlet_id')->constrained()->cascadeOnDelete();

            /*
             * URL-safe random, 32+ bytes. Never sequential — a guessable code
             * would let anyone fabricate presence at an outlet.
             */
            $table->string('token', 64)->unique();

            $table->enum('mode', ['printed', 'rotating']);

            // NULL for printed codes: valid until revoked.
            $table->timestamp('expires_at')->nullable();

            $table->timestamp('revoked_at')->nullable();
            $table->foreignId('revoked_by')->nullable()->constrained('users')->nullOnDelete();

            // NULL when auto-generated by a display device rather than a person.
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();

            // Rotating only: how many times this outlet has rolled its code.
            $table->unsignedBigInteger('generations')->default(0);

            $table->timestamps();

            $table->index(['outlet_id', 'expires_at']);
            $table->index('revoked_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('outlet_tokens');
    }
};
